### ISSUE TITLE
Validate the correctness on a trained network by pytorch

### ISSUE THREAD

**Issue by ziqi-zhang** [facebookresearch/CrypTen#307]
Hi,

I want to check the correctness of a network trained by pytorch in plaintext. I used the plaintext evaluation function, but directly convert the model to private model and the input to encrypted input as follows:
```
def construct_private_model(input_size, model):
    """Encrypt and validate trained model for multi-party setting."""
    # get rank of current process
    # rank = comm.get().get_rank()
    rank = 0
    dummy_input = torch.empty(input_size)

    # party 0 always gets the actual model; remaining parties get dummy model
    if rank == 0:
        model_upd = model
    else:
        model_upd = LeNet()
    private_model = crypten.nn.from_pytorch(model_upd, dummy_input).encrypt(src=0)
    return private_model


def encrypt_data_tensor_with_src(input):
    """Encrypt data tensor for multi-party setting"""
    # get rank of current process
    # rank = comm.get().get_rank()
    # get world size
    # world_size = comm.get().get_world_size()
    rank, world_size = 0, 1

    if world_size > 1:
        # party 1 gets the actual tensor; remaining parties get dummy tensor
        src_id = 1
    else:
        # party 0 gets the actual tensor since world size is 1
        src_id = 0

    if rank == src_id:
        input_upd = input
    else:
        input_upd = torch.empty(input.size())
    private_input = crypten.cryptensor(input_upd, src=src_id)
    return private_input
```
I did not use multi-processing but only used one main process because I found multi-processing is difficult to debug. I hard-coded the rank and world size.

The correctness of encrypted model is different from the plaintext model. I was wondering is it because  I only used one process or the error is caused by the fixed-point number encodings?

Best Wishes,

**Comment by ziqi-zhang** [comment]
The pytorch version is 1..9.0 and the model is ResNet18. I checked that the inference on cpu is correct but the model output is different on GPUs. Besides, I also checked the cifar example and found that it is correct on both cpu and GPUs. So is the implementation between ResNet and LeNet different on GPUs?

**Comment by knottb** [comment]
Could you please provide the inference code you are running and a log of output comparisons between plaintext and crypten models. In my experience these models should produce roughly the same output (within quantization error).

**Comment by ziqi-zhang** [comment]
The inference code is following
```

def test_crypten(model, test_loader, criterion, device, epoch=0., silent=False, writer=None):
    model.eval()
    test_loss = 0.
    correct = 0
    total = 0
    t_start = time.time()
    
    # determin to use cpu or cuda
    cuda = False
    
    input_size = get_input_size(test_loader, )
    if not cuda:
        model = model.cpu()
    private_model = construct_private_model(input_size, model, cuda=cuda)

    with torch.no_grad():
        for batch_idx, (inputs, targets) in enumerate(test_loader):
            inputs = encrypt_data_tensor_with_src(inputs)
            if cuda:
                inputs, targets = inputs.to(device), targets.to(device)
            encrypted_outputs = private_model(inputs)
            outputs = encrypted_outputs.get_plain_text()
            nclasses = outputs.size(1)

            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()
            
            if (batch_idx+1) % 1 == 0:
                acc = 100. * correct / total
                t_cur = time.time()
                time_elapsed = int(t_cur - t_start)
                time_per_batch = time_elapsed / (batch_idx + 1)
                print(f"[{batch_idx} / {len(test_loader)}] Acc: {acc:.2f}({correct}/{total}) TotalTime: {time_elapsed:.4f}s TimePerBatch: {time_per_batch:.4f}s")
            
    t_end = time.time()
    t_epoch = int(t_end - t_start)
    time_per_batch = t_epoch / len(test_loader)

    acc = 100. * correct / total
    test_loss /= total

    print(f"[Test]  Acc: {acc:.2f}% ({correct}/{total}) TotalTime: {t_epoch:.4f}s TimePerBatch: {time_per_batch:.4f}")

    return test_loss, acc
```

The decrypted output on cpu is (batch size = 1, output dimension = 200) normal:
```
tensor([[14.6258,  7.5329, 11.6402, -0.4084,  3.7167,  1.1450, -0.8259,  4.8801,
         -0.6376, -0.8635,  3.1122,  1.9051, -2.0512, -1.7493, -2.6403, -2.3806,
         -0.6286, -1.6674, -0.9431, -0.2662, -3.4791,  0.8092,  8.3746,  2.1538,
          4.4764, -1.1105, -2.4270, -1.4398, -2.0546,  2.0682,  0.4076,  0.9340,
         -1.1711,  0.2196, -0.8695, -0.9065, -0.7137, -1.3317, -3.3456, -1.6960,
         -1.7750, -2.7103, -1.9942,  2.1259,  9.6854,  3.5873, -1.5639, -0.4105,
          3.4361, -1.6236,  0.1257,  1.9248, -0.0837, -0.8980,  0.1464, -1.1334,
         -2.6676,  5.1245,  2.7657,  2.3257,  3.8702,  4.2246,  2.5150,  0.5288,
          4.9922,  3.5350, -2.2094, -1.2873, -1.3222, -2.9922,  7.1066,  8.7747,
          0.6010, -0.0879, -0.4291, -0.6517,  0.3197, -0.4998, -2.7053, -0.9755,
          1.0750, -2.1956, -0.1862,  6.1284,  1.3920,  4.6568,  1.4808, -0.8296,
          0.7669,  0.8772, -1.2454, -0.4478,  1.9397, -0.7845, -1.1263, -1.4109,
          1.8089, -2.5789,  0.3251,  4.2030,  0.2983,  0.5215, -0.0885,  0.2551,
         -3.4486,  1.9759,  0.7131,  0.1557, -2.3431,  1.0297, -2.1428,  1.4766,
         -1.2409, -0.1941, -1.9590, -0.5846, -3.4084, -0.9335, -5.8108,  0.7237,
         -1.2142, -2.8369, -5.1920, -3.5737, -1.9836, -2.2065, -2.6177, -2.5160,
         -3.4817, -1.3491,  0.3839, -2.5040, -2.6228, -1.1123,  5.0393,  0.4038,
          1.4985,  1.7374, -2.0391,  0.7892, -0.8220,  3.9594,  2.6509,  1.4453,
         -0.9365,  0.5907, -0.3402, -2.6619, -1.3026, -3.1329, -2.7600, -1.4748,
          1.1201, -1.2837,  1.1078, -0.5644,  1.6914, -2.2327, -2.6999, -2.8821,
          0.0586, -2.0953, -4.0538, -1.6115, -5.0764, -0.1740, -0.7044,  0.7558,
         -2.3114, -1.3729, -1.3210, -2.0259, -0.2265, -3.4308, -1.0168, -2.1729,
         -0.2811,  1.3783,  0.9042, -1.0849,  2.2080, -1.9070, -2.8643,  0.9067,
          0.6001,  3.1567, -1.7243, -0.8416, -1.2299,  1.3272, -3.2349, -2.1473,
          0.7511, -2.5914,  1.9108, -0.1510, -1.5094, -1.7468,  1.7815, -0.8148]])
```
The decrypted output on GPUs is abnormal and the values are very large
```
tensor([[-2.5287e+05, -5.6729e+05, -1.0657e+06, -2.4245e+06,  1.4755e+06,
         -1.3250e+06, -3.0377e+03,  4.6502e+04, -6.8726e+05,  1.4417e+06,
         -7.6545e+05,  1.7146e+06, -2.2324e+06, -9.8900e+05, -5.0693e+05,
          2.7369e+06,  3.2058e+06, -7.2486e+05, -1.3958e+06,  2.1822e+06,
          2.8686e+05, -5.8565e+05, -5.5272e+04, -1.1958e+05, -5.6420e+05,
         -2.0269e+05,  5.8374e+05, -1.2611e+06,  7.9788e+05, -7.0881e+05,
          3.8194e+05, -1.1673e+06, -2.1818e+06, -9.7960e+05,  5.4844e+05,
          9.9032e+05, -2.6889e+06, -1.0185e+06, -1.3514e+06, -1.1959e+06,
          1.0546e+06,  2.6614e+06, -9.8839e+05,  3.2254e+06,  1.8941e+05,
         -3.1052e+05,  9.6847e+05,  2.7674e+06, -2.7812e+04, -1.4218e+06,
          3.3253e+05, -1.5676e+06, -1.7553e+06,  2.6802e+05,  1.2967e+06,
          3.4897e+05,  6.7338e+05,  2.4139e+06,  1.6442e+05, -1.1709e+05,
          2.8003e+06,  1.4649e+06,  2.0724e+06, -5.3547e+05, -1.1114e+06,
          1.3684e+06, -1.0568e+06, -4.2792e+05,  2.0759e+05, -1.6974e+06,
          8.9771e+05, -1.1645e+06,  1.3354e+06, -5.5665e+05,  8.5893e+05,
         -7.1383e+05,  1.6038e+06, -7.4778e+05,  2.9353e+05, -1.9240e+06,
          4.6788e+05,  3.2869e+05, -1.1478e+05,  1.0414e+06,  2.2485e+06,
         -1.9252e+06, -4.4697e+05,  6.6509e+05, -1.7952e+06, -6.2381e+05,
          8.3060e+05, -1.0378e+06, -3.2763e+05, -1.3353e+06,  2.5219e+06,
          2.4702e+06,  1.9275e+06,  1.0647e+06,  1.8724e+06, -1.1666e+06,
          3.4819e+05, -1.2154e+06,  3.4413e+04,  1.8061e+06, -1.7092e+06,
          1.9846e+06,  7.8738e+05, -1.6974e+05, -3.9983e+05, -1.1992e+06,
         -5.2145e+05, -1.3756e+06, -1.6158e+06,  7.6164e+05, -1.7448e+06,
         -1.2200e+06,  2.0799e+05, -6.6767e+05, -1.7487e+05,  1.9277e+05,
          3.5248e+05, -1.3776e+05, -9.6432e+05, -3.5662e+05, -9.7760e+05,
         -1.1590e+06,  9.8714e+05, -3.3886e+05, -2.5014e+05, -2.1519e+06,
         -1.3171e+06,  3.6192e+05, -1.7518e+06,  2.2838e+05, -1.3921e+06,
         -3.6302e+05, -5.5547e+05, -1.0829e+06,  1.7535e+06,  2.0382e+06,
          1.3300e+06, -5.2094e+04,  3.5062e+06,  1.4109e+05,  1.9032e+05,
          2.8071e+06,  7.4067e+05,  1.5056e+06,  9.3531e+05, -6.3133e+05,
         -1.9188e+06, -1.6023e+06, -2.6782e+06, -5.8865e+05, -2.2929e+06,
         -6.9490e+05, -1.3096e+06, -9.8965e+05, -7.6332e+05, -1.9955e+06,
         -1.2212e+06, -1.4476e+05,  6.8817e+05, -2.0033e+06, -2.2146e+06,
          4.8572e+05,  7.1822e+05,  1.3099e+06,  1.3666e+06,  4.5708e+05,
         -7.7964e+05,  1.7061e+06,  3.3565e+05,  1.5779e+06, -2.0081e+04,
          6.3135e+05,  9.6612e+05,  1.1773e+05, -6.4059e+05, -3.5093e+05,
          7.1526e+05,  7.2615e+05,  1.1079e+05,  1.3240e+06, -5.7929e+05,
          2.8770e+05, -1.5903e+06,  2.8223e+05,  7.2001e+05,  1.7403e+05,
          9.6773e+05,  1.2352e+06, -2.4133e+06,  1.8157e+06,  9.2554e+05,
         -2.1614e+06, -7.4312e+05, -1.1644e+06, -8.3117e+05,  1.9831e+06]],
       device='cuda:0')
```

**Comment by knottb** [comment]
What is the model you are using? These output values appear to be quite large which may indicate a potential issue with the dynamic range of the approximations within the model. 

Also does this work correctly on CPU?

**Comment by ziqi-zhang** [comment]
The model is ResNet18 from pytorch pretrained library. Yes, this work is correct on CPU but incorrect on GPU. Besides, I also tried LeNet and it is correct on both CPU and GPU. I guess it may be caused by the BatchNorm on GPU?

**Comment by lvdmaaten** [comment]
Hmmm interesting. The implementation of the operators is identical between CPU and GPU, so that shouldn't be the problem. There are small differences between the implementations in the CPU and GPU backends of PyTorch but I'd be surprised that they would lead to differences this large. (You could try setting `torch.use_deterministic_algorithms(True)` to see if it makes a difference.) 

So perhaps the most likely culprit may be in the logic that converts long values into floats before computation on the GPU, and back afterwards? @knottb Could there be some subtlety there that we missed, maybe in the implementation of the division operation (which is used in batch normalization)?

**Comment by knottb** [comment]
I believe the division operation should be identical on CPU and GPU. It is possible that for certain sizes, the multiplication logic fails on GPU, but I haven't seen this happen in practice. I'll note that it does look like most of the results have roughly the same magnitude, which could imply an overflow issue during multiplication / accumulation?

**Comment by ziqi-zhang** [comment]
I think maybe I need to try to trace the internal features of CPU models and GPU models and locate the first layer that has different output. But if the error is caused by the overflow, can I change the data type of weights and inputs to solve this problem?

**Comment by knottb** [comment]
That shouldn't affect the result since CrypTen changes the data type of the input under the hood in order to use fixed-point encoding.

**Comment by ziqi-zhang** [comment]
I tried to trace the features and found that the output after layer2 is consistent but the output after layer3 is incorrect. It seems like there is an overflow error in the layer3 .

**Comment by knottb** [comment]
Do you happen to have large weights in layer 3. Overflow is much more likely when the magnitude of a product or matrix multiply is large.

**Comment by ziqi-zhang** [comment]
Hi @knottb  , I arranged a piece of code to replicate this bug. The model is a public ResNet18. The pytorch version is 1.8.0 and CrypTenis the latest version. 
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils import data as torch_data
from torch.utils.data import Dataset, DataLoader, Subset
from pretrainedmodels import resnet18

import crypten


def encrypt_data_tensor_with_src(input):
    # get rank of current process
    # rank = comm.get().get_rank()
    # get world size
    # world_size = comm.get().get_world_size()
    rank, world_size = 0, 1
    if world_size > 1:
        # party 1 gets the actual tensor; remaining parties get dummy tensor
        src_id = 1
    else:
        # party 0 gets the actual tensor since world size is 1
        src_id = 0
    if rank == src_id:
        input_upd = input
    else:
        input_upd = torch.empty(input.size())
    private_input = crypten.cryptensor(input_upd, src=src_id)
    return private_input

def get_input_size(val_loader,):
    input, target = next(iter(val_loader))
    return input.size()

def construct_private_model(input_size, model, cuda=False):
    # get rank of current process
    # rank = comm.get().get_rank()
    rank = 0
    dummy_input = torch.empty(input_size)
    if cuda:
        dummy_input = dummy_input.cuda()
    
    # party 0 always gets the actual model; remaining parties get dummy model
    if rank == 0:
        model_upd = model
    else:
        model_upd = LeNet()
    private_model = crypten.nn.from_pytorch(model_upd, dummy_input).encrypt(src=0)
    if cuda:
        private_model = private_model.cuda()
    return private_model


def test_simple(model, crypt=True, cuda=False):
    crypten.init()
    
    inputs = torch.zeros((8,3,224,224))
    model.eval()
    if cuda:
        model = model.cuda()
    else:
        model = model.cpu()
    
    if crypt:
        private_model = construct_private_model((8,3,224,224), model, cuda=cuda)
        inputs = encrypt_data_tensor_with_src(inputs)
    else:
        private_model = model
    if cuda:
        inputs = inputs.cuda()
        
    encrypted_outputs = private_model(inputs)
    if crypt:
        outputs = encrypted_outputs.get_plain_text()
    else:
        outputs = encrypted_outputs
    return outputs

def main():
    model = resnet18()

    cpu_outputs = test_simple(model, )
    print(f"CPU outputs:")
    print(cpu_outputs)
    cuda_outputs = test_simple(model, cuda=True)
    print(f"CUDA outputs:")
    print(cuda_outputs)

if __name__ == '__main__':
    main()

```

The output is 
```
CPU outputs:
tensor([[-0.0662,  0.6181, -1.9341,  ..., -1.3664, -0.0125,  0.3454],
        [-0.0662,  0.6181, -1.9341,  ..., -1.3664, -0.0125,  0.3454],
        [-0.0662,  0.6181, -1.9341,  ..., -1.3664, -0.0125,  0.3454],
        ...,
        [-0.0662,  0.6181, -1.9341,  ..., -1.3664, -0.0125,  0.3454],
        [-0.0662,  0.6181, -1.9341,  ..., -1.3664, -0.0125,  0.3454],
        [-0.0662,  0.6181, -1.9341,  ..., -1.3664, -0.0125,  0.3454]])
CUDA outputs:
tensor([[ 1.3739e+05,  6.6404e+04, -1.3835e+06,  ..., -1.3045e+06,
          6.8822e+05, -5.8368e+05],
        [ 5.3062e+05,  2.8928e+05, -1.3098e+06,  ..., -9.7912e+05,
          3.4955e+05, -2.2701e+05],
        [ 2.2703e+02,  5.1336e+05, -9.0261e+05,  ..., -8.1339e+05,
          3.7458e+05,  3.8588e+05],
        ...,
        [ 6.9278e+04,  2.4135e+05, -7.2775e+05,  ..., -4.9445e+05,
          2.8241e+05,  8.2983e+04],
        [ 1.5655e+05,  1.7781e+05, -9.6646e+05,  ..., -7.3632e+05,
          3.2757e+05, -1.1853e+05],
        [ 6.2528e+05,  3.7473e+05, -8.9086e+05,  ..., -6.0216e+05,
          4.5073e+05,  4.8378e+05]], device='cuda:0')
```
The CPU output is normal but the CUDA output overflows.

**Comment by knottb** [comment]
I don't currently have a GPU machine on hand to debug this so it could take a while. However, my initial thought is this could be caused by some trouble with fan-out logic in the cuda_tensor code.

If you could, can you test this with the following line changed:

https://github.com/facebookresearch/CrypTen/blob/main/crypten/cuda/cuda_tensor.py#L202

If you change this line to `nb = 4`, I imagine this could possibly fix the problem. 

The issue here is described in Remark II.1 of https://arxiv.org/pdf/2104.10949.pdf. It's possible that the threshold we are using is not small enough despite adhering to the protocol shown in the paper.

Do you happen to have a layer with a number of neurons around 256?

**Comment by ziqi-zhang** [comment]
Yes, you are right! I changed that line and the problem is fixed. The model I used has several layers with 256 neurons at layer3, which is the exact layer to have an incorrect output feature.

**Comment by knottb** [comment]
Interesting. I'll have to dig deeper into this line. I'll mark this as a bug and check this a bit later.

Could you provide a file with the model in it for debugging purposes?

**Comment by ziqi-zhang** [comment]
The latest script is a runnable file. It uses the public resnet18 that will be automatically downloaded from Internet. The package ``pretrainedmodels'' can be installed via
```
pip install pretrainedmodels
```

**Comment by hobbitlzy** [comment]
Hi, is there any progress on this problem? Is it safe to just use this solution?

> I don't currently have a GPU machine on hand to debug this so it could take a while. However, my initial thought is this could be caused by some trouble with fan-out logic in the cuda_tensor code.
> 
> If you could, can you test this with the following lines changed:
> 
> * https://github.com/facebookresearch/CrypTen/blob/main/crypten/cuda/cuda_tensor.py#L202
> * https://github.com/facebookresearch/CrypTen/blob/main/crypten/cuda/cuda_tensor.py#L245
> 
> If you change these line to `nb = 4`, I imagine this could possibly fix the problem.
> 
> The issue here is described in Remark II.1 of https://arxiv.org/pdf/2104.10949.pdf. It's possible that the threshold we are using is not small enough despite adhering to the protocol shown in the paper.
> 
> Do you happen to have a layer with a number of neurons around 256?

**Comment by kwmaeng91** [comment]
Still experiencing this problem as of 0.4.1. The above fix worked.
